In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import pickle

# Data

In [2]:
path1 = './DECOR/data/news_features/gossipcop_bert_raw_768d.pkl'

with open(path1, "rb") as file:
    gossip_raw = pickle.load(file)

gossip_raw

tensor([[-0.7062, -0.6844, -0.9906,  ..., -0.9636, -0.6996,  0.6779],
        [-0.3680, -0.4791, -0.9859,  ..., -0.9070, -0.5233, -0.1027],
        [-0.6067, -0.7932, -0.9919,  ..., -0.9854, -0.6792,  0.6363],
        ...,
        [-0.5886, -0.3794, -0.7214,  ..., -0.2210, -0.3680,  0.2341],
        [-0.5542, -0.7504, -0.9949,  ..., -0.9155, -0.7100,  0.3699],
        [-0.1170, -0.5801, -0.9337,  ..., -0.6493, -0.5680,  0.1875]],
       device='cuda:0')

In [3]:
gossip_raw.shape

torch.Size([16599, 768])

In [4]:
path2 = './DECOR/data/news_features/politifact_bert_raw_768d.pkl'

with open(path2, "rb") as file:
    politifact_raw = pickle.load(file)

politifact_raw

tensor([[-0.8490, -0.7208, -0.9943,  ..., -0.9413, -0.7986,  0.5838],
        [-0.5307, -0.6317, -0.9670,  ..., -0.8867, -0.6794,  0.1861],
        [-0.5012, -0.5524, -0.9991,  ..., -0.9972, -0.5969, -0.4002],
        ...,
        [-0.3337, -0.5601, -0.9580,  ..., -0.7806, -0.5973,  0.1310],
        [-0.7714, -0.6591, -0.9247,  ..., -0.7253, -0.6287,  0.4494],
        [-0.7945, -0.5954, -0.9256,  ..., -0.6753, -0.5737,  0.3982]],
       device='cuda:0')

In [5]:
path3 = './DECOR/data/social_context_raw/gossipcop_raw.csv'

gossip_csv = pd.read_csv(path3)

gossip_csv.head(5)

sid  label                 tid                 uid
0  gossipcop-879076      0  908251744009949184  839815575538827264
1  gossipcop-879076      0  907243646902083584           199874723
2  gossipcop-879076      0  907303682731073538  839355885616939010
3  gossipcop-879076      0  907303066680152064          4874979999
4  gossipcop-879076      0  908256760275894272  844951679921537024

In [6]:
gossip_csv.shape

(963009, 4)

In [7]:
path4 = './DECOR/data/social_context_raw/politifact_raw.csv'

politifact_csv = pd.read_csv(path4)

politifact_csv.head(5)

sid  label                 tid         uid
0  politifact12773      0  742435361989656576    40105634
1  politifact12773      0  742473904707506176    21474769
2  politifact12773      0  749361217832181760   221019366
3  politifact12773      0  743219062243745793  2828847648
4  politifact12773      0  742050569993363456  2228433725

### user_news_graph
-A_un: the user engagement matrix of size [num_users, num_news]. Element [i,j] in the matrix represents the number of interactions between active user u_i (defined as users with at least 3 engagements) and news article p_j, in terms of the user's reposts of news article on social media. If an article receive no engagements from active users, it is assigned value of 1 with an unique index (this creates a self-loop for the article when we construct the news engagement graph).  
-uid_dict: contains the mapping from users' Twitter IDs to matrix indices, under the format {user_id:index}.  
-sid_dict: contains the mapping from FakeNewsNet news IDs to matrix indices, under the format {news_id:index}.

In [8]:
path5= './DECOR/data/user_news_graph/weighted/gossipcop_un_relations_t3_raw.pkl'

with open(path5, "rb") as file:
    gossip_new = pickle.load(file)

gossip_new

{'A_un': array([[2., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 0., 0., 0.],
        [2., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 'uid_dict': {839815575538827264: 0,
  199874723: 1,
  839355885616939010: 2,
  4874979999: 3,
  844951679921537024: 4,
  399422941: 5,
  839743041384538112: 6,
  4889543384: 7,
  390457914: 8,
  839505781942800384: 9,
  844966877075927040: 10,
  713385903461367809: 11,
  839519945180524544: 12,
  126744767: 13,
  846639835246817280: 14,
  16910607: 15,
  845110951737098240: 16,
  1006905289: 17,
  839772590252048384: 18,
  840524255024492544: 19,
  839728591143231488: 20,
  844978796339986433: 21,
  846648532274601984: 22,
  844923340909428736: 23,
  4889604194: 24,
  713061197411692544: 25,
  705108363386945536: 26,
  2471499625: 27,
  20587567: 28,
  709139627114889218: 29,
  2249784332: 30,
  38557052: 31,
  805989

In [9]:
path5= './DECOR/data/user_news_graph/weighted/politifact_un_relations_t3_raw.pkl'

with open(path5, "rb") as file:
    politifact_new = pickle.load(file)

politifact_new

{'A_un': array([[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [2., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 'uid_dict': {40105634: 0,
  21474769: 1,
  128334973: 2,
  1045337473: 3,
  369760961: 4,
  711102413374136320: 5,
  341027410: 6,
  402365122: 7,
  226248858: 8,
  3888351: 9,
  230028713: 10,
  2825578734: 11,
  1278597655: 12,
  1967626670: 13,
  44592655: 14,
  330040053: 15,
  3068394829: 16,
  485018010: 17,
  126600280: 18,
  24789345: 19,
  749556961: 20,
  124954559: 21,
  552135980: 22,
  15501305: 23,
  9695312: 24,
  2393490350: 25,
  40061315: 26,
  23322726: 27,
  2840710396: 28,
  198069904: 29,
  2466729240: 30,
  33469319: 31,
  177488853: 32,
  3907653083: 33,
  5392522: 34,
  16815644: 35,
  955474525: 36,
  873648944: 37,
  16950863: 38,
  23545095: 39,
  17134268: 40,
  22883463: 41,
  3433148488:

# Data Load

In [10]:
import pickle 
import torch
import pandas as pd
import numpy as np
from torch_geometric.data import Data



def load_graph_decor(obj, u_thres = 3):

    news_features = pickle.load(open('DECOR/data/news_features/' + obj + '_bert_raw_768d.pkl', 'rb'))
    graph_dict = pickle.load(open('DECOR/data/user_news_graph/weighted/' + obj + '_un_relations_t' + str(u_thres) + '_raw.pkl', 'rb'))
    mask_dict = pickle.load(open('DECOR/data/temp_splits/' + obj + '_train_test_mask_80_20_temp.pkl', 'rb'))

    train_mask, test_mask = mask_dict['train_mask'], mask_dict['test_mask']
    y_train, y_test = mask_dict['y_train'], mask_dict['y_test']
    A_un = torch.Tensor(graph_dict['A_un'])

    # DECOR thresholds the maximum number of engagement between a certain user and a certain article at 1% of num_news.
    s = round(A_un.shape[1] / 100)
    A_un_new = torch.where(A_un < s, A_un, torch.tensor(s, dtype=A_un.dtype))
    adj = A_un_new.transpose(0, 1).matmul(A_un_new)

    # degrees
    xdeg, ydeg = adj.sum(0), adj.sum(0)
    xdeg = xdeg.view(-1, 1)
    xdeg, ydeg = xdeg.repeat(1, adj.shape[0]), ydeg.repeat(adj.shape[1], 1)

    # co-engagement
    A_un_thres1 = torch.where(A_un < 1, A_un, torch.tensor(1., dtype=A_un.dtype))
    adj_thres1 = A_un_thres1.transpose(0, 1).matmul(A_un_thres1)


    return Data(x = news_features, adj = adj_thres1, xdeg = xdeg, ydeg = ydeg,
                train_mask = train_mask, test_mask = test_mask,
                y_train = y_train, y_test = y_test)


In [11]:
data_p = load_graph_decor('politifact')

In [12]:
data_p.x.shape #497 개의 nodes (기사), 768 개의 arc (feature - NLP embedding 의 결과)

torch.Size([497, 768])

In [13]:
data_p.adj.shape

torch.Size([497, 497])

In [14]:
data_g = load_graph_decor('gossipcop')

In [15]:
data_g.x #16599 개의 nodes (기사), 768 개의 arc (feature - NLP embedding 의 결과)

tensor([[-0.7062, -0.6844, -0.9906,  ..., -0.9636, -0.6996,  0.6779],
        [-0.3680, -0.4791, -0.9859,  ..., -0.9070, -0.5233, -0.1027],
        [-0.6067, -0.7932, -0.9919,  ..., -0.9854, -0.6792,  0.6363],
        ...,
        [-0.5886, -0.3794, -0.7214,  ..., -0.2210, -0.3680,  0.2341],
        [-0.5542, -0.7504, -0.9949,  ..., -0.9155, -0.7100,  0.3699],
        [-0.1170, -0.5801, -0.9337,  ..., -0.6493, -0.5680,  0.1875]],
       device='cuda:0')

In [16]:
data_g.x.shape

torch.Size([16599, 768])

In [17]:
data_g.adj # (news x user) X (user x news)

tensor([[49., 10., 10.,  ...,  0.,  0.,  0.],
        [10., 20., 10.,  ...,  0.,  1.,  0.],
        [10., 10., 21.,  ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0.,  ..., 47.,  0.,  0.],
        [ 0.,  1.,  0.,  ...,  0., 61.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  1.]])

In [18]:
data_g.adj.shape

torch.Size([16599, 16599])

# FakeNews Data

## Politifact

In [19]:
path1 = './FakeNewsNet/dataset/politifact_real.csv'
path2 = './FakeNewsNet/dataset/politifact_fake.csv'

politifact_real = pd.read_csv(path1)
politifact_real.head(5)

id                                           news_url  \
0  politifact14984                          http://www.nfib-sbet.org/   
1  politifact12944  http://www.cq.com/doc/newsmakertranscripts-494...   
2    politifact333  https://web.archive.org/web/20080204072132/htt...   
3   politifact4358  https://web.archive.org/web/20110811143753/htt...   
4    politifact779  https://web.archive.org/web/20070820164107/htt...   

                                               title  \
0        National Federation of Independent Business   
1                        comments in Fayetteville NC   
2  Romney makes pitch, hoping to close deal : Ele...   
3  Democratic Leaders Say House Democrats Are Uni...   
4    Budget of the United States Government, FY 2008   

                                           tweet_ids  
0  967132259869487105\t967164368768196609\t967215...  
1  942953459\t8980098198\t16253717352\t1668513250...  
2                                                NaN  
3                                                NaN  
4  89804710374154240\t91270460595109888\t96039619...

In [20]:
politifact_fake = pd.read_csv(path2)
politifact_fake.head(5)

id                                           news_url  \
0  politifact15014          speedtalk.com/forum/viewtopic.php?t=51650   
1  politifact15156  politics2020.info/index.php/2018/03/13/court-o...   
2  politifact14745  www.nscdscamps.org/blog/category/parenting/467...   
3  politifact14355  https://howafrica.com/oscar-pistorius-attempts...   
4  politifact15371  http://washingtonsources.org/trump-votes-for-d...   

                                               title  \
0  BREAKING: First NFL Team Declares Bankruptcy O...   
1  Court Orders Obama To Pay $400 Million In Rest...   
2  UPDATE: Second Roy Moore Accuser Works For Mic...   
3         Oscar Pistorius Attempts To Commit Suicide   
4        Trump Votes For Death Penalty For Being Gay   

                                           tweet_ids  
0  937349434668498944\t937379378006282240\t937380...  
1  972666281441878016\t972678396575559680\t972827...  
2  929405740732870656\t929439450400264192\t929439...  
3  886941526458347521\t887011300278194176\t887023...  
4  915205698212040704\t915242076681506816\t915249...

In [21]:
politifact_csv.head(5)

sid  label                 tid         uid
0  politifact12773      0  742435361989656576    40105634
1  politifact12773      0  742473904707506176    21474769
2  politifact12773      0  749361217832181760   221019366
3  politifact12773      0  743219062243745793  2828847648
4  politifact12773      0  742050569993363456  2228433725

In [22]:
politifact_real

id                                           news_url  \
0    politifact14984                          http://www.nfib-sbet.org/   
1    politifact12944  http://www.cq.com/doc/newsmakertranscripts-494...   
2      politifact333  https://web.archive.org/web/20080204072132/htt...   
3     politifact4358  https://web.archive.org/web/20110811143753/htt...   
4      politifact779  https://web.archive.org/web/20070820164107/htt...   
..               ...                                                ...   
619  politifact14731  https://www.flake.senate.gov/public/index.cfm/...   
620    politifact329  https://web.archive.org/web/20080131000131/htt...   
621   politifact1576         http://www.youtube.com/watch?v=4O8CxZ1OD58   
622   politifact4720         http://www.youtube.com/watch?v=EhyMplwY6HY   
623     politifact52  https://web.archive.org/web/20071102131244/htt...   

                                                 title  \
0          National Federation of Independent Business   
1                          comments in Fayetteville NC   
2    Romney makes pitch, hoping to close deal : Ele...   
3    Democratic Leaders Say House Democrats Are Uni...   
4      Budget of the United States Government, FY 2008   
..                                                 ...   
619  Flake: “Religious tests should have no place i...   
620                           Change We Can Believe In   
621  deputy director of national health statistics ...   
622  Romneys ProLife Conversion Myth or Reality Jun...   
623                             Interest Group Ratings   

                                             tweet_ids  
0    967132259869487105\t967164368768196609\t967215...  
1    942953459\t8980098198\t16253717352\t1668513250...  
2                                                  NaN  
3                                                  NaN  
4    89804710374154240\t91270460595109888\t96039619...  
..                                                 ...  
619                                                NaN  
620  634287923135909888\t946743411100536832\t946816...  
621                                                NaN  
622                                 188871706637647874  
623           1002208963239337984\t1024651239697666048  

[624 rows x 4 columns]

In [23]:
poli_url = pd.DataFrame(politifact_csv["sid"].unique(), columns=["sid"])
poli_url["news_url"]=""
for i in range(len(poli_url)):
    if poli_url["sid"][i] in list(politifact_real["id"]):
        poli_url["news_url"][i] = politifact_real[politifact_real["id"]== poli_url["sid"][i]]["news_url"].values[0]
    elif poli_url["sid"][i] in list(politifact_fake["id"]):
        poli_url["news_url"][i] = politifact_fake[politifact_fake["id"]== poli_url["sid"][i]]["news_url"].values[0]

poli_url

sid                                           news_url
0    politifact12773  https://www.washingtonpost.com/news/post-polit...
1      politifact495  http://www.cnn.com/2007/POLITICS/07/23/debate....
2    politifact14474  https://www.law.cornell.edu/constitution/amend...
3      politifact567  https://web.archive.org/web/20080709210822/htt...
4    politifact12052  https://www.washingtonpost.com/news/the-fix/wp...
..               ...                                                ...
492  politifact15349  https://www.hollywoodreporter.com/live-feed/da...
493  politifact15631  https://yournewswire.com/lisa-page-squeals-dnc...
494  politifact15630  https://madworldnews.com/hillary-dead-body-hum...
495  politifact15100  http://politicsdepot.com/2018/02/28/kushner-an...
496  politifact15354  https://exclusive103.com/2018/04/30/thousands-...

[497 rows x 2 columns]

In [35]:
poli_url["news_url"][2]

'https://www.law.cornell.edu/constitution/amendmentxxv'

In [36]:
import requests
from bs4 import BeautifulSoup

# URL 지정
url = poli_url["news_url"][0]

# URL로부터 HTML 가져오기
response = requests.get(url)

# HTML 파싱
soup = BeautifulSoup(response.text, 'html.parser')

h1_tags = soup.find('h1')
print(h1_tags.text)

‘Americans need to stand together’: Hillary Clinton’s remarks following the Orlando shooting


In [43]:
import requests
from bs4 import BeautifulSoup

count_n = 0
count_t = 0

poli_url["title"]=""
for i in range(len(poli_url)):
    url = poli_url["news_url"][i]
    try: 
        response = requests.get(url, timeout=10)
        soup = BeautifulSoup(response.text, 'html.parser')
        h1_tags = soup.find('h1')
        if h1_tags is None:
            poli_url["title"][i] = "None"
            count_n += 1
        else:
            poli_url["title"][i] = h1_tags.text
    except requests.exceptions.RequestException:
        poli_url["title"][i] = "Error"
        count_t += 1

print("정보가 없는 기사 개수:", count_n)
print("url 접속 안되는 기사 개수:", count_t)
poli_url

정보가 없는 기사 개수: 87
url 접속 안되는 기사 개수: 169


sid                                           news_url  \
0    politifact12773  https://www.washingtonpost.com/news/post-polit...   
1      politifact495  http://www.cnn.com/2007/POLITICS/07/23/debate....   
2    politifact14474  https://www.law.cornell.edu/constitution/amend...   
3      politifact567  https://web.archive.org/web/20080709210822/htt...   
4    politifact12052  https://www.washingtonpost.com/news/the-fix/wp...   
..               ...                                                ...   
492  politifact15349  https://www.hollywoodreporter.com/live-feed/da...   
493  politifact15631  https://yournewswire.com/lisa-page-squeals-dnc...   
494  politifact15630  https://madworldnews.com/hillary-dead-body-hum...   
495  politifact15100  http://politicsdepot.com/2018/02/28/kushner-an...   
496  politifact15354  https://exclusive103.com/2018/04/30/thousands-...   

                                                 title  
0                                                Error  
1      Part I: CNN/YouTube Democratic presidential ...  
2                                       25th Amendment  
3                                                 None  
4    The CNN Miami Republican debate transcript, an...  
..                                                 ...  
492  ‘The Daily Show’s’ Michelle Wolf Lands Her Own...  
493                                               None  
494                            \nPage not found (404)   
495                              Site is not available  
496                                               None  

[497 rows x 3 columns]

## Gossipcop

In [28]:
path3 = './FakeNewsNet/dataset/gossipcop_real.csv'
path4 = './FakeNewsNet/dataset/gossipcop_fake.csv'

gossipcop_real = pd.read_csv(path3)
gossipcop_real.head(5)

id                                           news_url  \
0  gossipcop-882573  https://www.brides.com/story/teen-mom-jenelle-...   
1  gossipcop-875924  https://www.dailymail.co.uk/tvshowbiz/article-...   
2  gossipcop-894416        https://en.wikipedia.org/wiki/Quinn_Perkins   
3  gossipcop-857248  https://www.refinery29.com/en-us/2018/03/19192...   
4  gossipcop-884684  https://www.cnn.com/2017/10/04/entertainment/c...   

                                               title  \
0  Teen Mom Star Jenelle Evans' Wedding Dress Is ...   
1  Kylie Jenner refusing to discuss Tyga on Life ...   
2                                      Quinn Perkins   
3  I Tried Kim Kardashian's Butt Workout & Am For...   
4  Celine Dion donates concert proceeds to Vegas ...   

                                           tweet_ids  
0  912371411146149888\t912371528343408641\t912372...  
1  901989917546426369\t901989992074969089\t901990...  
2  931263637246881792\t931265332022579201\t931265...  
3  868114761723936769\t868122567910936576\t868128...  
4  915528047004209152\t915529285171122176\t915530...

In [29]:
gossipcop_fake = pd.read_csv(path4)
gossipcop_fake.head(5)

id                                           news_url  \
0  gossipcop-2493749932  www.dailymail.co.uk/tvshowbiz/article-5874213/...   
1  gossipcop-4580247171  hollywoodlife.com/2018/05/05/paris-jackson-car...   
2   gossipcop-941805037  variety.com/2017/biz/news/tax-march-donald-tru...   
3  gossipcop-2547891536  www.dailymail.co.uk/femail/article-3499192/Do-...   
4  gossipcop-5476631226  variety.com/2018/film/news/list-2018-oscar-nom...   

                                               title  \
0  Did Miley Cyrus and Liam Hemsworth secretly ge...   
1  Paris Jackson & Cara Delevingne Enjoy Night Ou...   
2  Celebrities Join Tax March in Protest of Donal...   
3  Cindy Crawford's daughter Kaia Gerber wears a ...   
4      Full List of 2018 Oscar Nominations – Variety   

                                           tweet_ids  
0  284329075902926848\t284332744559968256\t284335...  
1  992895508267130880\t992897935418503169\t992899...  
2  853359353532829696\t853359576543920128\t853359...  
3  988821905196158981\t988824206556172288\t988825...  
4  955792793632432131\t955795063925301249\t955798...